The first effort to deploy EAGLE on Mac

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -4,7 +4,19 @@
 
 set -aeuo pipefail
 
-INSTALLDIR=$(readlink -f ${INSTALLDIR:-$PWD/conda})
+_realpath() {
+  if command -v python3 >/dev/null 2>&1; then
+    python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
+  elif command -v greadlink >/dev/null 2>&1; then
+    greadlink -f "$1"
+  elif command -v realpath >/dev/null 2>&1; then
+    realpath -m "$1" 2>/dev/null || realpath "$1"
+  else
+    perl -MCwd -e 'print Cwd::abs_path(shift)' "$1"
+  fi
+}
+
+INSTALLDIR=$(_realpath "${INSTALLDIR:-$PWD/conda}")
 
 # In all functions, make variables local unless they are either intended for global use, or set in
 # a subshell that exits at the end of the function.
@@ -16,17 +28,32 @@ cachedir() {
   )
 }
 
+env_file() {
+  local name=$1
+  if [ "$(uname -s)" = "Darwin" ] && [ -f "envs/$name.osx.yaml" ]; then
+    echo "envs/$name.osx.yaml"
+  else
+    echo "envs/$name.yaml"
+  fi
+}
+
 cuda_command_file() {
   local path val
-  val=${ARGS[cudascript]}
+  val=$CUDA_SCRIPT
   path=$val
-  test -e $path || path=$(dirname $(readlink -f $0))/cuda/$val
-  echo $path
+  test -e "$path" || path=$(dirname "$(_realpath "$0")")/cuda/$val
+  echo "$path"
 }
 
 cuda_release() {
   (
-    source $(cuda_command_file)
+    if ! command -v module >/dev/null 2>&1; then
+      return 0
+    fi
+    source "$(cuda_command_file)"
+    if ! command -v nvcc >/dev/null 2>&1; then
+      return 0
+    fi
     nvcc --version | grep release | sed -E 's/^.*release ([0-9]+).*/\1/'
   )
 }
@@ -63,18 +90,28 @@ install_conda() {
     msg Found existing conda installation: $INSTALLDIR
     return
   fi
+  local platform arch
   ver=26.1.1-3
-  installer=Miniforge3-$ver-$(uname -s)-$(uname -p).sh
+  platform=$(uname -s)
+  arch=$(uname -m)
+  if [ "$platform" = "Darwin" ]; then
+    platform=MacOSX
+  fi
+  installer=Miniforge3-$ver-$platform-$arch.sh
   url=https://github.com/conda-forge/miniforge/releases/download/$ver/$installer
   msg Installing conda
-  wget -nv $url
-  bash $installer -bfp $INSTALLDIR
-  rm -v $installer
+  if command -v wget >/dev/null 2>&1; then
+    wget -nv "$url"
+  else
+    curl -L -o "$installer" "$url"
+  fi
+  bash "$installer" -bfp "$INSTALLDIR"
+  rm -v "$installer"
 }
 
 install_devpkgs_maybe() {
   local name
-  if [[ -v EAGLEDEV ]]; then
+  if [ -n "${EAGLEDEV:-}" ]; then
     name=$1
     msg Installing dev packages into environment: $name
     (
@@ -89,23 +126,29 @@ msg() {
 }
 
 parse_kvargs() {
-  local arg key required val
-  declare -g -A ARGS
-  for arg in $@; do
-    IFS="=" read -r key val <<<$arg
-    ARGS[$key]=$val
+  local arg key val IFS
+  for arg in "$@"; do
+    IFS="="
+    read -r key val <<<"$arg"
+    case "$key" in
+      cudascript)
+        CUDA_SCRIPT="$val"
+        ;;
+      *)
+        eval "$key=\"$val\""
+        ;;
+    esac
   done
-  required="cudascript"
-  for arg in $required; do
-    test -z "${ARGS[$arg]:-}" && echo Argument $arg= missing && exit 1
-  done
-  export ARGS
+  if [ -z "${CUDA_SCRIPT:-}" ]; then
+    echo "Argument cudascript= missing"
+    exit 1
+  fi
 }
 
 prep_env() {
   local args name
   name=$1
-  args=(${MAMBAFLAGS[@]} --file envs/$name.yaml --name $name)
+  args=(${MAMBAFLAGS[@]} --file $(env_file "$name") --name $name)
   (
     env_activate base
     if env_exists $name; then
@@ -127,7 +170,7 @@ prep_env() {
     dir_activate=$CONDA_PREFIX/etc/conda/activate.d
     mkdir -pv $dir_activate
     cat <<EOF >$dir_activate/eagle.sh
-if [[ -v XDG_CACHE_HOME ]]; then
+if [ -n "${XDG_CACHE_HOME:-}" ]; then
   export EAGLE_OLD_XDG_CACHE_HOME=\$XDG_CACHE_HOME
 fi
 export XDG_CACHE_HOME=$(cachedir)
@@ -136,7 +179,7 @@ EOF
     mkdir -pv $dir_deactivate
     cat <<EOF >$dir_deactivate/eagle.sh
 unset XDG_CACHE_HOME
-if [[ -v EAGLE_OLD_XDG_CACHE_HOME ]]; then
+if [ -n "${EAGLE_OLD_XDG_CACHE_HOME:-}" ]; then
   export XDG_CACHE_HOME=\$EAGLE_OLD_XDG_CACHE_HOME
   unset EAGLE_OLD_XDG_CACHE_HOME
 fi
@@ -150,7 +193,7 @@ prep_env_base() {
   (
     env_activate $name
     msg Updating environment: $name
-    mamba env update ${MAMBAFLAGS[@]} --file envs/$name.yaml
+    mamba env update ${MAMBAFLAGS[@]} --file $(env_file "$name")
     install_devpkgs_maybe $name
   )
 }
@@ -166,7 +209,7 @@ prep_env_data() {
     mkdir -pv $dir_activate
     # NB: Append to the existing script:
     cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
-if [[ -v FI_PSM3_UUID ]]; then
+if [ -n "${FI_PSM3_UUID:-}" ]; then
   export EAGLE_OLD_FI_PSM3_UUID=\$FI_PSM3_UUID
 fi
 export FI_PSM3_UUID=eagle
@@ -176,7 +219,7 @@ EOF
     # NB: Append to the existing script:
     cat <<EOF >>$dir_deactivate/eagle.sh
 unset FI_PSM3_UUID
-if [[ -v EAGLE_OLD_FI_PSM3_UUID ]]; then
+if [ -n "${EAGLE_OLD_FI_PSM3_UUID:-}" ]; then
   export FI_PSM3_UUID=\$EAGLE_OLD_FI_PSM3_UUID
   unset EAGLE_OLD_FI_PSM3_UUID
 fi
@@ -217,7 +260,7 @@ write_anemoi_activation_scripts() {
     # NB: Append to the existing script:
     cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
 modules="\$(module --terse list 2>/dev/null | grep -v 'No modules loaded' | tr '\n' ' ')"
-if [[ -n "\$modules" ]]; then
+if [ -n "\$modules" ]; then
   export EAGLE_OLD_MODULES="\$modules"
 fi
 $(cat $(cuda_command_file))
@@ -225,7 +268,7 @@ EOF
     # NB: Append to the existing script:
     cat <<EOF >>$CONDA_PREFIX/etc/conda/deactivate.d/eagle.sh
 module purge 2>/dev/null
-if [[ -v EAGLE_OLD_MODULES ]]; then
+if [ -n "${EAGLE_OLD_MODULES:-}" ]; then
   module load \$EAGLE_OLD_MODULES
   unset EAGLE_OLD_MODULES
 fi
@@ -240,7 +283,12 @@ MAMBAFLAGS=(--log-level error --yes)
 MAMBA_ROOT_PREFIX=$INSTALLDIR
 XDG_CACHE_HOME=$(cachedir)
 export CONDA_OVERRIDE_CUDA MAMBA_ROOT_PREFIX XDG_CACHE_HOME
-environments=(base data inference prewxvx training visualization wxvx)
+if [ "$(uname -s)" = "Darwin" ]; then
+  environments=(base data inference prewxvx training visualization)
+  echo "=> Darwin detected: skipping wxvx environment because required package met2go is unavailable on macOS"
+else
+  environments=(base data inference prewxvx training visualization wxvx)
+fi
 for name in ${environments[@]}; do
   time prep_env_$name
 done
